### ISSUE TITLE
Travis CI: Assembler: Error: no such instruction

### ISSUE THREAD

**Issue by eriknellessen** [eriknellessen/Selbstauskunft-in-the-middle#1]
When compiling cryptopp (when building eIDClientCore), the following error message occurs:
`g++ -DNDEBUG -g2 -O2 -fPIC -march=native -pipe -c nbtheory.cpp
{standard input}: Assembler messages:
{standard input}:34682: Error: no such instruction: `vfmsub312sd .LC9(%rip),%xmm0,%xmm3'
{standard input}:34725: Error: no such instruction: `vfmsub312sd .LC9(%rip),%xmm0,%xmm3'`
This problem is discussed [here](https://github.com/Theano/Theano/issues/3780).

This error does not occur in the eIDClientCore project. This is probably, because it uses the new [container based infrastructure](https://docs.travis-ci.com/user/workers/container-based-infrastructure/). We can not do that in this project, because we need apache2-dev, which is not on the Travis CI package whitelist, see [here](https://github.com/travis-ci/apt-package-whitelist/issues/1501).

**Comment by nouiz** [comment]
You can use work around by setting Theano flags. Try one of those. The first one is the safest, but probably slowest:

```
gcc.cxxflags='-march=core2"
gcc.cxxflags='-march=corei7"
gcc.cxxflags='-march=corei7-avx"
```

We have an issue to test what g++ tell us to use.

Ho, wait, I think you don't use Theano? The problem is that g++ badly detect frequently new CPU instructions set. Remove the -march=native flags and it should work. You can replace it by the suggestion I gave above.

**Comment by eriknellessen** [comment]
Thank you for your help. I will have to change the way cryptopp is build when building eIDClientCore (e.g. by using sed on the cryptopp Makefiles before building).

Actually, I referenced your issue, because it explained the cause for this error, so I would understand, what the problem is, when I come back to this problem.

**Comment by eriknellessen** [comment]
Issue is no relevant anymore, because the project switched to GitLab CI.
